services:
  flask:
    image: two-tier-backend:latest
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=vicky
      - MYSQL_PASSWORD=vicky123
      - MYSQL_DB=devops
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root@1234
      - MYSQL_DATABASE=devops
      - MYSQL_USER=vicky
      - MYSQL_PASSWORD=vicky123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=vicky
      - PMA_PASSWORD=vicky123
    depends_on:
      - mysql
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:


