version: '3.8'

services:
  flask:
    image: two-tier-backend:latest
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=vicky
      - MYSQL_PASSWORD=vicky123
      - MYSQL_DB=devops
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root@1234
      - MYSQL_DATABASE=devops        # ✅ Corrected from MYSQL_DB
      - MYSQL_USER=vicky             # ✅ Added
      - MYSQL_PASSWORD=vicky123      # ✅ Added
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork                    # ✅ Added to share network with other containers

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - mynetwork                    # ✅ Added to same network

volumes:
  mysql_data:

networks:
  mynetwork:

