name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and start services with Docker Compose
      run: |
        docker compose up -d --build
        sleep 15  # Wait for services to stabilize

    - name: Check running containers
      run: docker ps

    - name: Health Check – Flask App (inside container)
      run: |
        docker compose exec -T flask curl --retry 5 --retry-connrefused --retry-delay 2 http://localhost:5000/

    - name: Stop all containers
      if: always()
      run: docker compose down
