name: Build and Test Flask App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build custom flask image
      run: |
        docker build -t two-tier-backend:latest .

    - name: Docker Compose up
      run: |
        docker compose up -d --build
        sleep 10
        docker ps

    - name: Test Flask app health
      run: |
        curl --retry 5 --retry-connrefused --retry-delay 2 http://localhost:5000 || exit 1

    - name: Tear down
      if: always()
      run: docker compose down

