name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and start services with Docker Compose
      run: |
        docker compose up -d --build

    - name: Wait for Flask to be ready
      run: |
        echo "Waiting for Flask to become available on port 5000..."
        for i in {1..10}; do
          if curl -s http://localhost:5000/ > /dev/null; then
            echo "Flask is up!"
            exit 0
          else
            echo "Retry $i: Flask not available yet..."
            docker compose ps
            sleep 5
          fi
        done
        echo "Flask app failed to start."
        docker compose logs
        exit 1

    - name: Show container status
      run: docker compose ps

    - name: Stop all containers
      if: always()
      run: docker compose down --volumes
